# Generated by Django 3.2.7 on 2021-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateTimeField(),
        ),
    ]
